-- @description This is for input tests of matrix_block_mult.
-- @madlib-param matrix_b = "NULL"
-- @madlib-param matrix_a = "'madlibtestdata.matrix_block_100_100'"
-- @madlib-param matrix_r = "'__madlib_temp_40418089_1365619947_6556506__'"
        set client_min_messages to error;
SET
        select madlib.matrix_block_mult(
            'madlibtestdata.matrix_block_100_100', NULL, '__madlib_temp_40418089_1365619947_6556506__');
psql:/Users/qianh1/workspace/madlib_testsuite/tests/Matrix/sql_MatrixBlockInputTestCase3/test_matrix_block_input3_4.sql:10: ERROR:  plpy.Error: Input error: Table name is invalid (plpython.c:4648)
CONTEXT:  Traceback (most recent call last):
  PL/Python function "matrix_block_mult", line 26, in <module>
    matrix_a, matrix_b, matrix_r)
  PL/Python function "matrix_block_mult", line 455, in matrix_block_mult
  PL/Python function "matrix_block_mult", line 52, in __validate_block
  PL/Python function "matrix_block_mult", line 14, in __is_tbl_exists
PL/Python function "matrix_block_mult"
      
