plpy.SPIError: column "badcolumnnamey" does not exist (plpython.c:4648)