-- @description This is for output tests of correlation.
-- @madlib-param target_cols = "NULL"
-- @madlib-param tbl_output = "'__madlib_temp_40418089_1365619947_6556506__'"
-- @madlib-param dataset = "''"
          set client_min_messages to error;
SET
          select output_table, row_count from
          madlib.correlation(
              '',
              '__madlib_temp_40418089_1365619947_6556506__',
              NULL);
psql:/Users/qianh1/workspace/madlib_testsuite/tests/Correlation/sql_input/test_correlation_input_test_49.sql:12: ERROR:  plpy.Error: (plpython.c:4648)
DETAIL:  Correlation error: Invalid source table name
CONTEXT:  Traceback (most recent call last):
  PL/Python function "correlation", line 25, in <module>
    return correlation.correlation(schema_madlib, source_table, output_table, target_cols)
  PL/Python function "correlation", line 28, in correlation
  PL/Python function "correlation", line 86, in _validate_corr_arg
PL/Python function "correlation"
          
